// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  tick: __t.u64(),
  targetName: __t.string().name("target_name"),
  behavior: __t.string(),
  sabotageKind: __t.string().name("sabotage_kind"),
  reasoning: __t.string(),
  taunt: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
