// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  shooter: __t.u32(),
  target: __t.identity(),
  hit: __t.bool(),
  lethal: __t.bool(),
  ox: __t.f32(),
  oy: __t.f32(),
  oz: __t.f32(),
  tx: __t.f32(),
  ty: __t.f32(),
  tz: __t.f32(),
  createdAt: __t.timestamp().name("created_at"),
});
