// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const DirectorLog = __t.object("DirectorLog", {
  id: __t.u64(),
  roomId: __t.u64(),
  tick: __t.u64(),
  targetName: __t.string(),
  behavior: __t.string(),
  sabotageKind: __t.string(),
  reasoning: __t.string(),
  taunt: __t.string(),
  createdAt: __t.timestamp(),
});
export type DirectorLog = __Infer<typeof DirectorLog>;

export const FavorLedger = __t.object("FavorLedger", {
  identity: __t.identity(),
  roomId: __t.u64(),
  favor: __t.f32(),
  updatedAt: __t.timestamp(),
});
export type FavorLedger = __Infer<typeof FavorLedger>;

export const LobbyPrompt = __t.object("LobbyPrompt", {
  id: __t.u64(),
  roomId: __t.u64(),
  player: __t.identity(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type LobbyPrompt = __Infer<typeof LobbyPrompt>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  roomId: __t.u64(),
  name: __t.string(),
  color: __t.u32(),
  skin: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  roll: __t.f32(),
  speed: __t.f32(),
  alive: __t.bool(),
  finished: __t.bool(),
  score: __t.i32(),
  online: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const Predator = __t.object("Predator", {
  roomId: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  targetPlayer: __t.identity(),
  behavior: __t.string(),
  speed: __t.f32(),
  active: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type Predator = __Infer<typeof Predator>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  code: __t.string(),
  mode: __t.string(),
  state: __t.string(),
  seed: __t.u32(),
  host: __t.identity(),
  tick: __t.u64(),
  playerCount: __t.u32(),
  createdAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const SabotageEvent = __t.object("SabotageEvent", {
  id: __t.u64(),
  roomId: __t.u64(),
  target: __t.identity(),
  kind: __t.string(),
  magnitude: __t.f32(),
  durationMs: __t.u32(),
  reason: __t.string(),
  createdAt: __t.timestamp(),
});
export type SabotageEvent = __Infer<typeof SabotageEvent>;

export const Sidecar = __t.object("Sidecar", {
  id: __t.u64(),
  identity: __t.identity(),
  updatedAt: __t.timestamp(),
});
export type Sidecar = __Infer<typeof Sidecar>;

export const TickTimer = __t.object("TickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickTimer = __Infer<typeof TickTimer>;

export const WorldConfig = __t.object("WorldConfig", {
  roomId: __t.u64(),
  json: __t.string(),
  status: __t.string(),
  updatedAt: __t.timestamp(),
});
export type WorldConfig = __Infer<typeof WorldConfig>;

