// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Player = __t.object("Player", {
  identity: __t.identity(),
  roomId: __t.u64(),
  name: __t.string(),
  color: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  roll: __t.f32(),
  speed: __t.f32(),
  alive: __t.bool(),
  finished: __t.bool(),
  score: __t.i32(),
  online: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  code: __t.string(),
  mode: __t.string(),
  state: __t.string(),
  seed: __t.u32(),
  host: __t.identity(),
  tick: __t.u64(),
  playerCount: __t.u32(),
  createdAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const TickTimer = __t.object("TickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickTimer = __Infer<typeof TickTimer>;

